"""open と with によるテキストファイルの読み書きを確認するサンプル。"""

from pathlib import Path

UNIT_DIR = Path(__file__).parent
SAMPLE_DATA_DIR = UNIT_DIR / "sample_data"
GENERATED_DIR = SAMPLE_DATA_DIR / "generated"


def read_lines(path: Path) -> list[str]:
    """テキストファイルを読み込み、改行を取り除いた list を返す。"""
    # with を使うと、ファイルを開いた後の close を安全に任せられる。
    # encoding を指定しておくと、文字コードの前提が明確になる。
    with open(path, encoding="utf-8") as file:  # noqa: PTH123
        lines = file.readlines()

    return [line.rstrip("\n") for line in lines]


def write_text_file(path: Path, lines: list[str]) -> None:
    """複数行の文字列をテキストファイルとして書き込む。"""
    # mode="w" は、ファイルを新規作成または上書きする。
    # 存在しない親ディレクトリがある場合は事前に作る必要がある。
    with open(path, mode="w", encoding="utf-8") as file:  # noqa: PTH123
        for line in lines:
            file.write(line)
            file.write("\n")


def append_text_file(path: Path, line: str) -> None:
    """テキストファイルの末尾に1行追加する。"""
    # mode="a" は、ファイルの末尾に追記する。
    # 既存内容を消したくない場合に使う。
    with open(path, mode="a", encoding="utf-8") as file:  # noqa: PTH123
        file.write(line)
        file.write("\n")


def run_file_reading_and_writing() -> None:
    """open と with による読み書きを確認する。"""

    input_path = SAMPLE_DATA_DIR / "input_lines.txt"
    output_path = GENERATED_DIR / "cleaned_lines.txt"

    GENERATED_DIR.mkdir(exist_ok=True)

    original_lines = read_lines(input_path)
    print(f"original_lines: {original_lines}")

    # 空行や空白だけの行を除外する。
    cleaned_lines = []

    for line in original_lines:
        stripped_line = line.strip()

        if stripped_line != "":
            cleaned_lines.append(stripped_line)

    write_text_file(output_path, cleaned_lines)
    append_text_file(output_path, "Generated by Unit 07")

    written_lines = read_lines(output_path)

    print(f"cleaned_lines: {cleaned_lines}")
    print(f"written_lines: {written_lines}")
    print(f"output_path exists: {output_path.exists()}")

    assert original_lines == ["Python", "", "Java", "SQL", "  ", "Pathlib"]
    assert cleaned_lines == ["Python", "Java", "SQL", "Pathlib"]
    assert written_lines == [
        "Python",
        "Java",
        "SQL",
        "Pathlib",
        "Generated by Unit 07",
    ]
    assert output_path.exists()
